name:                project-euler
version:             0.1.0.0
github:              "Kohei-Wada/project-euler"
license:             BSD3
author:              "Kohei Wada"
maintainer:          "program3152019@gmail.com"
copyright:           "Kohei Wada"


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         
  Please see the README on GitHub at <https://github.com/githubuser/project-euler#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- extra
- text
- Unique
- split
- array

library:
  source-dirs: src 

executables:
  project-euler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-euler

tests:
  project-euler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-euler



